### ISSUE TITLE
Script fails when attempting to open an image that pillow cannot read as an image file

### ISSUE THREAD

**Issue by geirawsm** [geirawsm/swaylockcomics#1]
```
eDP connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 293mm x 165mm
Setting script directory to '/home/[user]/.cache/i3lockcomics'
Getting sys-directory: '/home/[user]/Nextcloud/pc/dotfiles/coding/git/i3lockcomics/i3lockcomics'
Comic not chosen, but randomly chose `dilbert`
Found today's file already saved, using that instead of downloading again.
Filter `morepixels` is not recognized
Using `blur` as standard
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/[user]/Nextcloud/pc/dotfiles/coding/git/i3lockcomics/i3lockcomics/__main__.py", line 304, in <module>
    main()
  File "/home/[user]/Nextcloud/pc/dotfiles/coding/git/i3lockcomics/i3lockcomics/__main__.py", line 223, in main
    call(['i3lock', '-i', scrot(strip)])
  File "/home/[user]/Nextcloud/pc/dotfiles/coding/git/i3lockcomics/i3lockcomics/__main__.py", line 161, in scrot
    img = Image.open(strip)
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 2930, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '/home/[user]/.cache/i3lockcomics/strips/dilbert-2020-08-23.jpg'
```

**Comment by geirawsm** [comment]
Probable solution would be to add a file check when it discovers already downloaded file:
https://github.com/armandg/i3lockcomics/blob/master/i3lockcomics/__main__.py#L216

**Comment by geirawsm** [comment]
OK now.
